# Generated by Django 3.0.2 on 2020-01-22 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroCurso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_curso', models.CharField(max_length=64)),
                ('validade_curso', models.IntegerField(default=365)),
                ('norma_curso', models.CharField(max_length=64)),
                ('carga_hora_curso', models.IntegerField()),
            ],
        ),
    ]
