# Generated by Django 3.0.2 on 2020-01-22 01:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_curso', '0001_initial'),
        ('cadastro_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroUnidades',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_unidade', models.CharField(max_length=64)),
                ('cursos_necesarios', models.ManyToManyField(to='cadastro_curso.cadastroCurso')),
            ],
        ),
        migrations.CreateModel(
            name='frenteProgramada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local_embarque', models.CharField(max_length=64)),
                ('data_ini_unidade', models.DateTimeField()),
                ('local_desembarque', models.CharField(max_length=64)),
                ('data_fim_unidade', models.DateTimeField()),
                ('nome_unidade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_da_unidade', to='cadastro_unidade.cadastroUnidades')),
                ('op_guincho_frente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_do_opGuincho', to='cadastro_funcionario.cadastroFuncionario')),
                ('op_oxcorte_frente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_do_opOxCorte', to='cadastro_funcionario.cadastroFuncionario')),
                ('rigger_a_frente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_do_1_rigger', to='cadastro_funcionario.cadastroFuncionario')),
                ('rigger_b_frente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_do_2_rigger', to='cadastro_funcionario.cadastroFuncionario')),
                ('sup_frente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nome_do_supervisor', to='cadastro_funcionario.cadastroFuncionario')),
            ],
        ),
    ]
