# Generated by Django 3.0.2 on 2020-01-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_unidade', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='frenteprogramada',
            name='data_fim_unidade',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='frenteprogramada',
            name='data_ini_unidade',
            field=models.DateField(),
        ),
    ]
