# Generated by Django 3.0.2 on 2020-01-22 01:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cadastro_curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='cadastroFuncionario',
            fields=[
                ('matricula_funcionario', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_completo_funcionario', models.CharField(max_length=64)),
                ('funcao_funcionario', models.CharField(max_length=64)),
                ('cpf_funcionario', models.IntegerField()),
                ('sispat_funcionario', models.IntegerField()),
                ('disponibilidade_funcionario', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='certificadoFuncionario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_realizada', models.DateTimeField()),
                ('valido_ate', models.DateTimeField()),
                ('curso_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_curso.cadastroCurso')),
                ('nome_funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cadastro_funcionario.cadastroFuncionario')),
            ],
        ),
    ]
