# Generated by Django 3.0.2 on 2020-01-26 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_funcionario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cadastrofuncionario',
            name='funcao_funcionario',
            field=models.CharField(choices=[['supervisor', 'Supervisor'], ['opGuincho', 'Operador de Guincho'], ['opOxCorte', 'Operador de OxCorte'], ['rigger', 'Rigger']], max_length=64),
        ),
    ]
