# Generated by Django 3.0.2 on 2020-01-28 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cadastro_funcionario', '0002_auto_20200125_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificadofuncionario',
            name='data_realizada',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='certificadofuncionario',
            name='valido_ate',
            field=models.DateField(),
        ),
    ]
